let items=[];let current=0;
const gallery=document.getElementById("gallery"),statusEl=document.getElementById("gallery-status"),hero=document.getElementById("hero-photo"),box=document.getElementById("lightbox"),boxImg=document.getElementById("lightbox-image");
document.getElementById("year").textContent=new Date().getFullYear();
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
async function load(){const r=await fetch("/api/images");if(!r.ok)throw new Error();const d=await r.json();items=d.images||[];const h=items.find(x=>x.hero);if(h)hero.style.backgroundImage=`url("${h.url}")`;statusEl.textContent=`${items.filter(x=>!x.hero).length} Moments`;const g=items.filter(x=>!x.hero);gallery.innerHTML=g.map((x,i)=>`<article class="gallery-card"><div class="image-wrap" data-i="${i}"><img src="${x.url}" alt="${esc(x.title)}" loading="lazy"></div><div class="caption"><span>${esc(x.category||"MOMENT")}</span><h3>${esc(x.title||"")}</h3></div></article>`).join("");gallery.querySelectorAll(".image-wrap").forEach(e=>e.onclick=()=>open(+e.dataset.i));}
function open(i){current=i;const g=items.filter(x=>!x.hero),x=g[i];boxImg.src=x.url;boxImg.alt=x.title||"";box.classList.add("open");document.body.classList.add("no-scroll")}
function close(){box.classList.remove("open");document.body.classList.remove("no-scroll")}
function move(d){const g=items.filter(x=>!x.hero);if(!g.length)return;current=(current+d+g.length)%g.length;boxImg.src=g[current].url;boxImg.alt=g[current].title||""}
document.getElementById("close-lightbox").onclick=close;document.getElementById("prev-image").onclick=()=>move(-1);document.getElementById("next-image").onclick=()=>move(1);box.onclick=e=>{if(e.target===box)close()};document.onkeydown=e=>{if(!box.classList.contains("open"))return;if(e.key==="Escape")close();if(e.key==="ArrowLeft")move(-1);if(e.key==="ArrowRight")move(1)};
load().catch(()=>{statusEl.textContent="Galerie nicht verfügbar";gallery.innerHTML='<div class="empty"><strong>Galerie konnte nicht geladen werden.</strong>Bitte prüfe die Cloudflare R2-Bindung.</div>'});
